# best is random(100, 1e-2)

# CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 1 --exp_type original  --render_mode rgbd_array --save_model 
# CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 1 --exp_type original --distillation random --distillation_scale 100 --distillation_lr 0.01 --render_mode rgbd_array --save_model 

CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 2 --exp_type original  --render_mode rgbd_array --save_model 
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 2 --exp_type original --distillation random --distillation_scale 100 --distillation_lr 0.01 --render_mode rgbd_array --save_model 

CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 3 --exp_type original  --render_mode rgbd_array --save_model 
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 3 --exp_type original --distillation random --distillation_scale 100 --distillation_lr 0.01 --render_mode rgbd_array --save_model 

CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 4 --exp_type original  --render_mode rgbd_array --save_model 
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 4 --exp_type original --distillation random --distillation_scale 100 --distillation_lr 0.01 --render_mode rgbd_array --save_model 

CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 5 --exp_type original  --render_mode rgbd_array --save_model 
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 5 --exp_type original --distillation random --distillation_scale 100 --distillation_lr 0.01 --render_mode rgbd_array --save_model 

CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 6 --exp_type original  --render_mode rgbd_array --save_model 
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 6 --exp_type original --distillation random --distillation_scale 100 --distillation_lr 0.01 --render_mode rgbd_array --save_model 

CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 7 --exp_type original  --render_mode rgbd_array --save_model 
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 7 --exp_type original --distillation random --distillation_scale 100 --distillation_lr 0.01 --render_mode rgbd_array --save_model 

CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 8 --exp_type original  --render_mode rgbd_array --save_model 
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 8 --exp_type original --distillation random --distillation_scale 100 --distillation_lr 0.01 --render_mode rgbd_array --save_model 

CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 9 --exp_type original  --render_mode rgbd_array --save_model 
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 9 --exp_type original --distillation random --distillation_scale 100 --distillation_lr 0.01 --render_mode rgbd_array --save_model 

CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 10 --exp_type original  --render_mode rgbd_array --save_model 
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name soccer-v2 --num_train_steps 620000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 10 --exp_type original --distillation random --distillation_scale 100 --distillation_lr 0.01 --render_mode rgbd_array --save_model 

