#!/bin/bash

CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name drawer-open-v2 --num_train_steps 420000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 1 --exp_type original --render_mode rgbd_array

# distillation lr [0.1, 0.01, 0.001]

# distillation scale [2000]
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name drawer-open-v2 --num_train_steps 420000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 1 --exp_type original --distillation encoder --distillation_scale 2000 --distillation_lr 0.1 --render_mode rgbd_array --save_model
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name drawer-open-v2 --num_train_steps 420000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 1 --exp_type original --distillation encoder --distillation_scale 2000 --distillation_lr 0.01 --render_mode rgbd_array --save_model
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name drawer-open-v2 --num_train_steps 420000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 1 --exp_type original --distillation encoder --distillation_scale 2000 --distillation_lr 0.001 --render_mode rgbd_array --save_model

# distillation scale [1000]
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name drawer-open-v2 --num_train_steps 420000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 1 --exp_type original --distillation encoder --distillation_scale 1000 --distillation_lr 0.1 --render_mode rgbd_array --save_model
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name drawer-open-v2 --num_train_steps 420000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 1 --exp_type original --distillation encoder --distillation_scale 1000 --distillation_lr 0.01 --render_mode rgbd_array --save_model 
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name drawer-open-v2 --num_train_steps 420000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 1 --exp_type original --distillation encoder --distillation_scale 1000 --distillation_lr 0.001 --render_mode rgbd_array --save_model 

# distillation scale [100]
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name drawer-open-v2 --num_train_steps 420000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 1 --exp_type original --distillation encoder --distillation_scale 100 --distillation_lr 0.1 --render_mode rgbd_array --save_model 
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name drawer-open-v2 --num_train_steps 420000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 1 --exp_type original --distillation encoder --distillation_scale 100 --distillation_lr 0.01 --render_mode rgbd_array --save_model 
CUDA_VISIBLE_DEVICES=0 python snerl/train.py --env_name drawer-open-v2 --num_train_steps 420000 --encoder_type nerf --save_tb --frame_stack 2 --eval_freq 10000 --batch_size 128 --save_video --save_model --image_size 128 --camera_name CUSTOM0 CUSTOM1 CUSTOM2 --multiview 3 --encoder_name 'snerl' --seed 1 --exp_type original --distillation encoder --distillation_scale 100 --distillation_lr 0.001 --render_mode rgbd_array --save_model